import Head from "next/head";
import { Inter } from "@next/font/google";
import Tech from "@/components/Tech";
import LandingPage from "@/components/LandingPage";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";
import { useState } from "react";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isNavActive, setNavActive] = useState(false);

  return (
    <>
      <Head>
        <title>Portofolio web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300;400;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className=" overflow-x-hidden scroll-smooth">
        {isNavActive && <Nav />}
        <LandingPage navActive={() => setNavActive(!isNavActive)} />
        <Tech />
        <Projects />
        <Contact />
      </main>
    </>
  );
}
